In [141]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
print(torch.__version__)

0.4.0


In [4]:
x = torch.DoubleTensor([1,1,1])

In [7]:
print(type(x))
x.type()

<class 'torch.Tensor'>


'torch.DoubleTensor'

In [8]:
y = torch.FloatTensor([[2,2],[3,3]])

In [13]:
y.requires_grad = True

In [14]:
y.requires_grad

True

In [18]:
x = torch.ones(1)
y = torch.ones(1)

In [19]:
x.requires_grad

False

In [20]:
y.requires_grad

False

In [21]:
z = x+y

In [25]:
z.requires_grad = True

In [26]:
z.backward()

In [27]:
z.grad

tensor([ 1.])

In [28]:
z2 = z + torch.ones(1)

In [30]:
z2.requires_grad
z2.backward()

In [31]:
z2.data

tensor([ 3.])

In [32]:
z2

tensor([ 3.])

In [59]:
a = torch.tensor([1,2,3.], requires_grad = True)

In [60]:
out = a.sigmoid()
out

tensor([ 0.7311,  0.8808,  0.9526])

In [43]:
c = out.detach()
c

tensor([ 0.7311,  0.8808,  0.9526])

In [44]:
c.zero_()

tensor([ 0.,  0.,  0.])

In [45]:
out

tensor([ 0.,  0.,  0.])

In [61]:
out2= out.sum().backward()
out2

In [62]:
## support 0 dimensinal scalar tensors

In [68]:
torch.tensor(3.1415)

tensor(3.1415)

In [77]:
a=torch.tensor(3.1415)
print(a.type())
a.size()

torch.FloatTensor


torch.Size([])

In [78]:
b = torch.tensor([3])
print(b.type())
b.size()

torch.LongTensor


torch.Size([1])

In [85]:
vector = torch.arange(2,6,step = 0.5)
vector

tensor([ 2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,  5.0000,
         5.5000])

In [86]:
vector.size()

torch.Size([8])

In [87]:
vector[4]

tensor(4.)

In [89]:
vector[4].item()

4.0

In [95]:
mysum = torch.tensor([2,3]).sum()

In [96]:
mysum

tensor(5)

In [99]:
b.item()

3

In [102]:
c.dtype

torch.float32

In [103]:
c.device

device(type='cpu')

In [106]:
c.layout

torch.strided

In [107]:
b.layout

torch.strided

In [112]:
device = torch.device("cpu")
device

device(type='cpu')

In [116]:
x = torch.randn(3, 3, dtype=torch.double, device=device)
x

tensor([[ 1.5635,  1.7093,  1.7533],
        [-0.1488, -0.4707, -1.6835],
        [ 0.8663,  0.9279, -0.5302]], dtype=torch.float64)

In [125]:
torch.tensor([1.33232323232232232,2.33232]).dtype

torch.float32

In [120]:
torch.tensor([1,2]).dtype

torch.int64

In [129]:
x = torch.randn(4, dtype=torch.float64)
x

tensor([-1.2275, -0.8243, -0.2566,  0.9070], dtype=torch.float64)

In [130]:
torch.zeros_like(x)

tensor([ 0.,  0.,  0.,  0.], dtype=torch.float64)

In [131]:
torch.ones_like(x)

tensor([ 1.,  1.,  1.,  1.], dtype=torch.float64)

In [135]:
torch.randn_like(x)

tensor([ 0.9412,  0.5831, -0.4946,  1.4030], dtype=torch.float64)

In [137]:
x = torch.randn(3, dtype=torch.float64)
x

tensor([ 0.5092, -0.0705, -0.4810], dtype=torch.float64)

In [138]:
x.new_ones(1)

tensor([ 1.], dtype=torch.float64)

In [139]:
x

tensor([ 0.5092, -0.0705, -0.4810], dtype=torch.float64)

In [142]:
a = np.array([1,2,3,4])

In [144]:
A = torch.from_numpy(a)
A

tensor([ 1,  2,  3,  4])

In [149]:
B = torch.zeros_like(A)
C = torch.ones_like(A)

In [150]:
A+B+C

tensor([ 2,  3,  4,  5])

In [151]:
torch.eye(3)

tensor([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.]])